# ═══════════════════════════════════════════════════════════════════════════
#                           APPLICATION CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════


application_settings:
  threads: 5
  ping_interval: 1200 # seconds (matches official Dawn extension v3.0.9)
  database_url: "sqlite://database.db" # SQlite or postgres, e.g. sqlite://database.db or postgres://user:password@localhost/dbname
  skip_logged_accounts: true
  shuffle_accounts: true
  check_uniqueness_of_proxies: true
  disable_auto_proxy_change: false # disable automatic proxy change for farming (for example for ISP proxy)


attempts_and_delay_settings:
  delay_before_start:
    min: 30 # seconds
    max: 60 # seconds

  error_delay: 60 # seconds
  max_login_attempts: 10
  max_stats_attempts: 3
  max_farm_attempts: 3


redirect_settings:
  enabled: false
  email: "your_redirect_email@gmail.com"
  password: "your_app_password"
  imap_server: "imap.gmail.com"
  use_proxy: false


imap_settings:
  use_proxy_for_imap: false

  use_single_imap:
    enable: false
    imap_server: "imap.gmail.com"

  servers:
    gmail.com: imap.gmail.com
    yahoo.com: imap.mail.yahoo.com
    icloud.com: imap.mail.me.com
    mail.ru: imap.mail.ru
    gmx.com: imap.gmx.com
    gmx.net: imap.gmx.net
    gmx.de: imap.gmx.net
    onet.pl: imap.poczta.onet.pl
    onet.com.pl: imap.poczta.onet.pl
    op.pl: imap.poczta.onet.pl
    onet.eu: imap.poczta.onet.pl
    gazeta.pl: imap.gazeta.pl


capsolver_settings:
  enabled: true
  api_key: "YOUR_CAPSOLVER_API_KEY"  # Get your API key from capsolver.com
