# ═══════════════════════════════════════════════════════════════════════════
#                           APPLICATION CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════


application_settings:
  threads: 10
  ping_interval: 1200 # seconds
  database_url: "sqlite://database/database.sqlite3" # SQlite or postgres, e.g. sqlite://database.db or postgres://user:password@localhost/dbname
  skip_logged_accounts: true
  shuffle_accounts: true
  check_uniqueness_of_proxies: true
  disable_auto_proxy_change: false # disable automatic proxy change for farming (for example for ISP proxy)
  use_random_ref_codes_from_db: false # use random referral codes from database instead of fixed ones


attempts_and_delay_settings:
  delay_before_start:
    min: 30 # seconds
    max: 60 # seconds

  error_delay: 10 # seconds
  max_login_attempts: 5
  max_stats_attempts: 3
  max_farm_attempts: 3
  max_captcha_attempts: 3
  max_tasks_attempts: 3


captcha_settings:
  max_captcha_solving_time: 180 # in seconds
  captcha_service: "2captcha" # options: capsolver, anti_captcha, 2captcha

  capsolver_api_key: ""
  anti_captcha_api_key: ""
  two_captcha_api_key: ""


redirect_settings:
  enabled: false
  email: ""
  password: ""
  imap_server: ""
  use_proxy: false


imap_settings:
  use_proxy_for_imap: false

  use_single_imap:
    enable: false
    imap_server: "imap.gmail.com"

  servers:
    gmail.com: imap.gmail.com
    yahoo.com: imap.mail.yahoo.com
    icloud.com: imap.mail.me.com
    mail.ru: imap.mail.ru
    gmx.com: imap.gmx.com
    gmx.net: imap.gmx.net
    gmx.de: imap.gmx.net
    onet.pl: imap.poczta.onet.pl
    onet.com.pl: imap.poczta.onet.pl
    op.pl: imap.poczta.onet.pl
    onet.eu: imap.poczta.onet.pl
    gazeta.pl: imap.gazeta.pl
